src/java/it/univr/booklovers/model/beans/ZoneBean.java
package it.univr.booklovers.model.beans;

import it.univr.booklovers.model.ZoneModel;
import java.io.Serializable;
import java.util.List;

/**
 *
 * @author Marian Solomon
 */
public class ZoneBean implements Serializable {

    private static final long serialVersionUID = 1L;

    /**
     *
     * @return
     */
    protected boolean isValid() {
        return (id != 0 && id != -1);
    }

    private int id;
    private String country;

    private String province;

    /**
     *
     */
    public ZoneBean() {
    }

    /**
     *
     * @param id
     * @param country
     * @param province
     */
    public ZoneBean(int id, String country, String province) {
        this.id = id;
        this.country = country;
        this.province = province;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }

    /**
     *
     * @return
     */
    public String getCountry() {
        return country;
    }

    /**
     *
     * @param country
     */
    public void setCountry(String country) {
        this.country = country;
    }

    /**
     *
     * @return
     */
    public String getProvince() {
        return province;
    }

    /**
     *
     * @param province
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public List<ZoneBean> getAllProvince() {
        return ZoneModel.getAllZone();
    }

}

src/java/it/univr/booklovers/controller/backend/AccountServlet.java
package it.univr.booklovers.controller.backend;

import it.univr.booklovers.controller.ServletModel;
import it.univr.booklovers.model.BookModel;
import it.univr.booklovers.model.UserModel;
import it.univr.booklovers.model.beans.UserBean;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.net.HttpURLConnection;
import java.net.URL;
import java.sql.SQLException;
import java.util.Map;
import javax.servlet.ServletException;
import javax.servlet.annotation.MultipartConfig;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ListaServlet
 */
@WebServlet(urlPatterns = {"/account"})
@MultipartConfig
public class AccountServlet extends ServletModel {

    private static final int BUFFER_LENGTH = 4096;
    private static final long serialVersionUID = 1L;

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) {
        String action = request.getParameter("action");
        action = action == null ? "index" : action;
        UserBean userBean = (UserBean) request.getSession().getAttribute("user");
        try {
            if (userBean != null && userBean.isLogged()) {
                request.setAttribute("books", BookModel.getAllBook(userBean.getId()));
                switch (action) {
                    case "edit":
                        request.setAttribute("form_destination", "account?action=" + action);
                        forward("backend/account_form.jsp", request, response);
                        break;
                    case "logout":
                        logout(request, response);
                        break;
                    case "signin":
                    case "login":
                        redirect("account?action=index", request, response);
                        break;
                    default: {
                        forward("backend/account.jsp", request, response);
                    }
                }
            } else {
                switch (action) {
                    case "signin":
                        request.setAttribute("form_destination", "account?action=" + action);
                        forward("backend/account_form.jsp", request, response);
                        break;
                    case "login":
                        forward("backend/login.jsp", request, response);
                        break;
                    default:
                        redirect("account?action=login", request, response);
                }
            }
        } catch (SQLException ex) {
            exceptionHandler(ex, request, response);
        }
    }

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) {
        String action = request.getParameter("action");
        action = action == null ? "index" : action;
        UserBean userBean = (UserBean) request.getSession().getAttribute("user");
        if (userBean != null && userBean.isLogged()) {
            switch (action) {
                case "edit":
                    edit(request, response);
                    break;
                case "editImage":
                    editImage(request, response);
                    break;
                case "login":
                case "signin":
                default:
                    doGet(request, response);
            }
        } else {
            switch (action) {
                case "signin":
                    signIn(request, response);
                    break;
                case "edit":
                case "login":
                    login(request, response);
                    break;
                default:
                    doGet(request, response);
            }
        }
    }

    private void edit(HttpServletRequest request, HttpServletResponse response) {
        UserBean accountBean = (UserBean) request.getSession().getAttribute("user");
        if (accountBean != null && accountBean.isLogged()) {
            try {
                Map<String, String> errors = validate(request.getParameterMap(), accountBean, UserBean.class);
                if (errors.isEmpty()) {
                    set(request.getParameterMap(), accountBean, UserBean.class);
                    UserModel.editUser(accountBean);
                    request.getSession().setAttribute("user", accountBean);
                    request.setAttribute("books", BookModel.getAllBook(accountBean.getId()));
                    redirect("account?action=index", request, response);

                } else {
                    request.setAttribute("errors", errors);
                    request.setAttribute("form_destination", "account?action=edit");
                    forward("backend/account_form.jsp", request, response);
                }
            } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException | SQLException ex) {
                exceptionHandler(ex, request, response);
            }
        } else {
            redirect("account?action=login", request, response);
        }
    }

    private void editImage(HttpServletRequest request, HttpServletResponse response) {
        String fileSaved = "img/profile-img.png";
        try {
            fileSaved = saveFile(request.getPart("profile-img"), "img/users/");
            UserBean userBean = (UserBean) request.getSession().getAttribute("user");
            userBean.setImage(fileSaved);
            UserModel.editUserImage(fileSaved, userBean.getId());
            int statusCode = 0;
            while (statusCode != 200) {
                URL url = new URL("http://" + request.getServerName() + ':' + request.getServerPort() + request.getContextPath() + '/' + fileSaved);
                HttpURLConnection http = (HttpURLConnection) url.openConnection();
                statusCode = http.getResponseCode();
            }
            redirect("account", request, response);

        } catch (IOException | SQLException | ServletException ex) {
            exceptionHandler(ex, request, response);
        }
    }

    private void login(HttpServletRequest request, HttpServletResponse response) {

        String email = request.getParameter("email");
        String password = request.getParameter("password");

        UserBean accountBean = null;
        try {
            accountBean = UserModel.getUser(email, "email");

            if (accountBean != null && password.equals(accountBean.getPassword())) {
                request.getSession().setAttribute("user", accountBean);
                request.setAttribute("books", BookModel.getAllBook(accountBean.getId()));
                redirect("account?action=index", request, response);
            } else {
                request.setAttribute("errors", "Email o password errati");
                forward("backend/login.jsp", request, response);
            }
        } catch (SQLException ex) {
            exceptionHandler(ex, request, response);
        }
    }

    private void logout(HttpServletRequest request, HttpServletResponse response) {
        request.getSession().removeAttribute("user");
        redirect("homepage", request, response);
    }

    private void signIn(HttpServletRequest request, HttpServletResponse response) {
        UserBean accountBean = (UserBean) request.getSession().getAttribute("user");
        try {
            Map<String, String> errors = validate(request.getParameterMap(), accountBean, UserBean.class);
            set(request.getParameterMap(), accountBean, UserBean.class);
            if (errors.isEmpty()) {
                UserModel.insertUser(accountBean);
                request.getSession().setAttribute("user", accountBean);
                redirect("account?action=index", request, response);
            } else {
                request.setAttribute("errors", errors);
                request.setAttribute("form_destination", "account?action=signin");
                forward("backend/account_form.jsp", request, response);
            }
        } catch (IllegalAccessException | IllegalArgumentException | InvocationTargetException | SQLException ex) {
            exceptionHandler(ex, request, response);
        }
    }

}

src/java/it/univr/booklovers/controller/backend/DataLoadServlet.java
package it.univr.booklovers.controller.backend;

import it.univr.booklovers.controller.ServletModel;
import it.univr.booklovers.model.Model;
import java.io.*;
import java.nio.charset.Charset;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author blasco991
 */
@WebServlet(urlPatterns = {"/load-data"})
public class DataLoadServlet extends ServletModel {

    private static final long serialVersionUID = 1L;

    /**
     *
     * @param request
     * @param response
     * @throws ServletException
     * @throws IOException
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
        executeQuery(loadQuery("../resource/sql/create_db.sql"));
        response.getOutputStream().println("Resetting DB...");
        executeQuery(loadQuery("../resource/sql/insert_user.sql"));
        response.getOutputStream().println("Insert Users...");
        executeQuery(loadQuery("../resource/sql/insert_book.sql"));
        response.getOutputStream().println("Insert Books...");
        executeQuery(loadQuery("../resource/sql/insert_book_image.sql"));
        response.getOutputStream().println("Insert Book Images...");
        executeQuery(loadQuery("../resource/sql/insert_comment.sql"));
        response.getOutputStream().println("Insert Book Comments...");
    }

    private String loadQuery(String file) throws UnsupportedEncodingException, FileNotFoundException {
        final StringBuilder builder = new StringBuilder();
        String pathToFile = getClass().getClassLoader().getResource(file).getFile();
        try (BufferedReader br = new BufferedReader(new InputStreamReader(new FileInputStream(pathToFile), Charset.forName("UTF-8")))) {
            String line = br.readLine();
            for (int i = 0;
                    line != null; line = br.readLine(), i++) {
                builder.append(line);
            }
        } catch (IOException ex) {
            Logger.getLogger(DataLoadServlet.class.getName()).log(Level.SEVERE, null, ex);
        }
        return builder.toString();
    }

    private static void executeQuery(final String query) {
        try (Statement statement = Model.getConnection().createStatement()) {
            statement.executeUpdate(query);
        } catch (SQLException ex) {
            Logger.getLogger(DataLoadServlet.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}

src/java/it/univr/booklovers/controller/backend/ProfileServlet.java
package it.univr.booklovers.controller.backend;

import it.univr.booklovers.controller.ServletModel;
import it.univr.booklovers.model.BookModel;
import it.univr.booklovers.model.UserModel;
import it.univr.booklovers.model.beans.UserBean;
import java.sql.SQLException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ListaServlet
 */
@WebServlet(urlPatterns = {"/profile"})
public class ProfileServlet extends ServletModel {

    private static final long serialVersionUID = 1L;

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) {
        UserBean userBean = (UserBean) request.getSession().getAttribute("user");

        if (userBean != null && userBean.isLogged()) {

            int id = 0;
            String profile_id = request.getParameter("id");
            if (profile_id != null && !profile_id.isEmpty()) {
                try {
                    id = Integer.parseInt(profile_id);
                } catch (NumberFormatException ex) {
                    exceptionHandler(ex, request, response);
                }
            }
            String username = request.getParameter("username");
            if (username != null && !username.isEmpty()) {
                try {
                    id = UserModel.getUser(username).getId();
                } catch (SQLException ex) {
                    exceptionHandler(ex, request, response);
                }
            }
            loadProfile(request, response, id);
        } else {
            redirect("account?action=login", request, response);
        }
    }

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) {
        doGet(request, response);
    }

    /**
     *
     * @param criterias
     */
    private void loadProfile(HttpServletRequest request, HttpServletResponse response, int profile_id) {
        try {
            UserBean profile = UserModel.getUser(profile_id);
            if (profile != null) {
                UserModel.updateUserView(profile.getId());
                request.setAttribute("profile", profile);
                request.setAttribute("books", BookModel.getAllBook(profile.getId()));
                forward("backend/profile.jsp", request, response);
            } else {
                redirect("backend/error_page.jsp", request, response);
            }
        } catch (NullPointerException | SQLException ex) {
            exceptionHandler(ex, request, response);
        }
    }

}

web/backend/account.jsp
<%@page import="it.univr.booklovers.model.beans.ZoneBean"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>


<jsp:useBean id="user" class="it.univr.booklovers.model.beans.UserBean" scope="session"/>

<t:header>
    <jsp:attribute name="pageTitle">BookLovers.com</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="row jumbotron">
            <div class="col-md-6 caption">
                <p class="lead">Benvenuto ${user.username}</p>
                <div class="list-group col-lg-5">
                    <a href="account?action=edit"><button type="button" class="list-group-item">Modifica i tuoi dati</button></a>
                    <a href="account/library?action=add"><button type="button" class="list-group-item">Aggiungi libro</button></a>
                    <a href="statistics"><button type="button" class="list-group-item">Vedi le statistiche</button></a>
                </div>
            </div>
            <div class="col-md-6">
                <t:user>
                    <jsp:attribute name="img">${user.image}</jsp:attribute>
                    <jsp:attribute name="name">${user.name}</jsp:attribute>
                    <jsp:attribute name="surname">${user.surname}</jsp:attribute>
                    <jsp:attribute name="email">${user.email}</jsp:attribute>
                    <jsp:attribute name="username">${user.username}</jsp:attribute>
                    <jsp:attribute name="province">${user.province}</jsp:attribute>
                    <jsp:body><br/>
                        <form action="account?action=editImage" method="POST" enctype="multipart/form-data" id="formEditImage">
                            <span class="btn btn-success btn-file">
                                Modifica foto profilo<input type="file" name="profile-img" id="profile-img" onchange="this.form.submit()"/>
                            </span>
                        </form>
                    </jsp:body>
                </t:user>
            </div>
        </div>
        <h2>La tua libreria</h2>
        <c:if test="${empty books}">
            <div class="col-lg-9 col-md-8 col-sm-7 col-xs-9 lead top-buffer-30">La ricerca non ha prodotto nessun risultato</div>
        </c:if>
        <div class="grid">  
            <c:forEach var="bk" items="${books}">
                <div class="col-lg-3 col-md-4 col-sm-5 col-xs-6 grid-item">
                    <t:book-thumb>
                        <jsp:attribute name="id">${bk.id}</jsp:attribute>
                        <jsp:attribute name="year">${bk.year}</jsp:attribute>
                        <jsp:attribute name="title">${bk.title}</jsp:attribute>
                        <jsp:attribute name="genre">${bk.genre}</jsp:attribute>
                        <jsp:attribute name="author">${bk.author}</jsp:attribute>
                        <jsp:attribute name="copertina">${bk.thumb}</jsp:attribute>
                        <jsp:attribute name="publisher">${bk.publisher}</jsp:attribute>
                        <jsp:attribute name="owner_id">${bk.owner.id}</jsp:attribute>
                        <jsp:attribute name="owner_username">${bk.owner.username}</jsp:attribute>
                        <jsp:body>
                            <a href="account/library?action=remove&book_id=${bk.id}" class="btn btn-danger" role="button">Rimuovi</a>
                            <a href="account/library?action=edit&book_id=${bk.id}" class="btn btn-warning" role="button">Modifica</a>
                        </jsp:body>
                    </t:book-thumb>
                </div>
            </c:forEach>
        </div>
    </jsp:body>

</t:page_content>

<t:footer></t:footer>

web/backend/account_form.jsp
<%@page import="it.univr.booklovers.model.beans.ZoneBean"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<jsp:useBean id="user" class="it.univr.booklovers.model.beans.UserBean" scope="session"/>
<jsp:useBean id="zone" class="it.univr.booklovers.model.beans.ZoneBean" scope="page" />

<t:header>
    <jsp:attribute name="pageTitle">Registrazione</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="top-buffer-30">
            <form class="form-horizontal" action='${requestScope.form_destination}' method="post" id="formAccount">
                <div class="form-group ${not empty errors.name ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="name">Nome</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="name" name="name" value="${user.name}" maxlength="64" placeholder="Nome" class="form-control">
                        <span class="control-label">${errors.name}</span>
                    </div>
                </div>
                <div class="form-group ${not empty errors.surname ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="surname">Cognome</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="surname" name="surname" value="${user.surname}" maxlength="64" placeholder="Cognome" class="form-control">
                        <span class="control-label">${errors.surname}</span>
                    </div>
                </div>  
                <div class="form-group ${not empty errors.postalCode ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="postalCode">Cap</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="postalCode" name="postalCode" value="${user.postalCode}" maxlength="32" placeholder="Cap" class="form-control">
                        <span class="control-label">${errors.postalCode}</span>
                    </div>
                </div>  
                <div class="form-group ${not empty errors.province ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="province">Provincia</label>
                    <div class="col-md-5 col-xs-8">
                        <select class="form-control" id="province" name="province" required="required">
                            <option disabled="disabled" selected="selected" value="">Selezione Provincia</option>
                            <c:forEach items="${zone.allProvince}" var="zn">
                                <option value="${zn.province}" ${(user.province == zn.province)?"selected='selected'":""}>${zn.province}</option> 
                            </c:forEach>
                        </select>
                        <span class="control-label">${errors.province}</span>
                    </div>
                </div>
                <div class="form-group ${not empty errors.coordinates ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="coordinates">Coordinate</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="coordinates" name="coordinates" value="${user.coordinates}" maxlength="64" placeholder="Coordinate" class="form-control">
                        <span class="control-label">${errors.coordinates}</span>
                    </div>
                    <script>
                        $(document).ready(function () {
                            var x = document.getElementById("coordinates");
                            if (navigator.geolocation) {
                                navigator.geolocation.getCurrentPosition(showPosition, error);
                            } else {
                                x.value = "Geolocalizzazzione fallita";
                            }

                            function showPosition(position) {
                                x.value = position.coords.latitude + ',' + position.coords.longitude;
                            }
                            function error(position) {
                                x.value = "Geolocalizzazzione bloccata dal browser";
                            }
                        });
                    </script>
                </div>
                <div class="form-group ${not empty errors.username ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="username">Username</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="username" name="username" value="${user.username}" maxlength="64" placeholder="Username" class="form-control">
                        <span class="control-label">${errors.username}</span>
                    </div>
                </div>
                <div class="form-group ${not empty errors.email ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="email">E-mail</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="text" id="email" name="email" value="${user.email}" maxlength="256" placeholder="E-mail" class="form-control">
                        <span class="control-label">${errors.email}</span>
                    </div>
                </div>
                <div class="form-group ${not empty errors.password ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="password">Password</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="password" id="inputPassword" name="inputPassword" placeholder="Password" maxlength="256" class="form-control">
                        <input type="hidden" id="password" name="password"/>
                        <span class="control-label">${errors.password}</span>
                    </div>
                </div>
                <div class="form-group ${not empty errors.confirmPassword ? 'has-error':''}">
                    <label class="col-md-4 col-xs-4 control-label" for="confirmPassword">Password (Confirm)</label>
                    <div class="col-md-5 col-xs-8">
                        <input type="password" id="inputConfirmPassword" name="inputConfirmPassword" placeholder="Conferma Password" maxlength="256" class="form-control">
                        <input type="hidden" id="confirmPassword" name="confirmPassword"/>
                        <span class="control-label">${errors.confirmPassword}</span>
                    </div>
                </div>
                <div class="form-group">
                    <button class="btn btn-success col-xs-8 col-md-4 col-md-offset-4 col-xs-offset-2">Invia</button>
                </div>
                <script type="text/javascript">
                    $(function () {
                        $('#inputPassword').change(function () {
                            $('#password').val(CryptoJS.SHA512($('#inputPassword').val()));
                        });
                        $('#inputConfirmPassword').change(function () {
                            $('#confirmPassword').val(CryptoJS.SHA512($('#inputConfirmPassword').val()));
                        });
                    });
                </script>
            </form>
        </div>
    </jsp:body>

</t:page_content>

<t:footer>
</t:footer>

web/backend/login.jsp
<%@page import="it.univr.booklovers.model.beans.ZoneBean"%>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<t:header>
    <jsp:attribute name="pageTitle">Login</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="top-buffer-100">
            <div class="col-md-6 col-md-offset-1">
                <div class="panel panel-info">
                    <div class="panel-heading">Entra con email e password</div>
                    <div class="panel-body">
                        <form class="form-horizontal" action='account?action=login' method="post">
                            <div class="form-group ${not empty errors ? 'has-error':''}">
                                <label class="col-xs-3 control-label" for="email">E-mail</label>
                                <div class="col-xs-9">
                                    <input type="text" id="email" name="email" value="${user.email}" placeholder="E-mail" class="form-control"/>
                                </div>
                            </div>
                            <div class="form-group ${not empty errors ? 'has-error':''}">
                                <label class="col-xs-3 control-label" for="password">Password</label>
                                <div class="col-xs-9">
                                    <input type="password" id="inputPassword" name="inputPassword" placeholder="Password" class="form-control"/>
                                    <input type="hidden" id="password" name="password" />
                                </div>
                            </div>
                            <button class="btn btn-success col-xs-4 col-xs-offset-4" type="submit">Login</button>
                            <script type="text/javascript">
                                $(function () {
                                    $('#inputPassword').change(function () {
                                        $('#password').val(CryptoJS.SHA512($('#inputPassword').val()));
                                    });
                                });
                            </script>  
                        </form>
                    </div>
                    <div class="panel-footer">
                        <span class="text-danger" ${empty errors ? 'hidden':''}>${errors}</span>&nbsp
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-info">
                    <div class="panel-heading">Registrati!</div>
                    <div class="panel-body">
                        <p class="well-sm">Se non hai ancora un account sul nostro portale crealo subito!</p>
                        <a href="account?action=signin"><button class="btn btn-warning col-xs-4 col-xs-offset-4" type="submit">Registrati</button></a>
                    </div>
                </div>
            </div>
        </div>
    </jsp:body>

</t:page_content>

<t:footer/>