src/java/it/univr/booklovers/model/beans/BookBean.java
package it.univr.booklovers.model.beans;

import it.univr.booklovers.model.BookModel;
import it.univr.booklovers.model.UserModel;
import java.sql.SQLException;
import java.util.*;

/**
 *
 * @author blasco991
 *
 */
public class BookBean {

    private String author;
    private String description;
    private String genre;
    private int id;
    private List<String> images = new ArrayList<>();
    private String isbn;
    private String language;
    private UserBean owner;
    private String publisher;
    private String title;
    private int views;
    private int year = Calendar.getInstance().get(Calendar.YEAR);
    private static final String EMPTY = "";

    /**
     *
     * @return
     */
    public String getAuthor() {
        return author;
    }

    /**
     *
     * @param author
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     *
     * @return
     */
    public String getDescription() {
        return description;
    }

    /**
     *
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     *
     * @return
     */
    public String getGenre() {
        return genre;
    }

    /**
     *
     * @param genre
     */
    public void setGenre(String genre) {
        this.genre = genre;
    }

    /**
     *
     * @return @throws java.sql.SQLException
     */
    public List<String> getGenres() throws SQLException {
        return BookModel.getAllGenre();
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public List<String> getImages() {
        return Collections.unmodifiableList(images);
    }

    /**
     *
     * @param images
     */
    public void setImages(List<String> images) {
        this.images = images;
    }

    /**
     *
     * @return
     */
    public String getIsbn() {
        return isbn;
    }

    /**
     *
     * @param isbn
     */
    public void setIsbn(String isbn) {
        this.isbn = isbn;
    }

    /**
     *
     * @return
     */
    public String getLanguage() {
        return language;
    }

    /**
     *
     * @param language
     */
    public void setLanguage(String language) {
        this.language = language;
    }

    /**
     *
     * @return
     */
    public UserBean getOwner() {
        return owner;
    }

    /**
     *
     * @param ownerID
     * @throws java.sql.SQLException
     */
    public void setOwner(String ownerID) throws SQLException {
        this.owner = UserModel.getUser(Integer.parseInt(ownerID));
    }

    /**
     *
     * @param owner
     */
    public void setOwner(UserBean owner) {
        this.owner = owner;
    }

    /**
     *
     * @return
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     *
     * @param publisher
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher;
    }

    /**
     *
     * @return
     */
    public String getThumb() {
        if (images.size() > 0) {
            return images.get(0);
        } else {
            return "img/image-not-found.png";
        }
    }

    /**
     *
     * @return
     */
    public String getTitle() {
        return title;
    }

    /**
     *
     * @param title
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     *
     * @return
     */
    public int getViews() {
        return views;
    }

    /**
     *
     * @param views
     */
    public void setViews(int views) {
        this.views = views;
    }

    /**
     *
     * @return
     */
    public int getYear() {
        return year;
    }

    /**
     *
     * @param year
     */
    public void setYear(int year) {
        this.year = year;
    }

    /**
     *
     * @param year
     */
    public void setYear(String year) {
        setYear(year.isEmpty() ? this.year :Integer.parseInt(year));
    }

    public static String validateAuthor(String author) {
        if (author == null || (author.length() < 3 || author.length() > 64)) {
            return "L'autore deve essere compreso tra 3 e 255 caratteri";
        }
        return EMPTY;
    }

    public static String validateDescription(String description) {
        if (description.length() > 200000) {
            return "La descrizione è troppo lunga";
        }
        return EMPTY;
    }

    public static String validateGenre(String genre) {
        if (genre == null || (genre.length() < 3 || genre.length() > 64)) {
            return "Il genere deve essere compreso tra 3 e 64 caratteri";
        }
        return EMPTY;
    }

    public static String validateIsbn(String isbn) {
        if (isbn == null || isbn.length() != 13) {
            return "L'isbn deve essere composto da 13 numeri";
        }
        return EMPTY;
    }

    public static String validateLanguage(String language) {
        if (language == null || (language.length() < 3 || language.length() > 32)) {
            return "La lingua deve essere compreso tra 3 e 32 caratteri";
        }
        return EMPTY;
    }

    public static String validateOwner(String ownerID) throws Exception {
        if (ownerID == null || Integer.parseInt(ownerID) < 1) {
            throw new Exception("OwnerID invalido durante l'inserimento di un libro");
        }
        return EMPTY;
    }

    public static String validatePublisher(String publisher) {
        if (publisher == null || (publisher.length() < 3 || publisher.length() > 64)) {
            return "L'editore deve essere compreso tra 3 e 64 caratteri";
        }
        return EMPTY;
    }

    public static String validateTitle(String title) {
        if (title == null || (title.length() < 1 || title.length() > 64)) {
            return "Il title deve essere compreso tra 3 e 64 caratteri";
        }
        return EMPTY;
    }

    public static String validateYear(String year) {
        if (year == null || year.isEmpty()) {
            return "Anno obbligatorio";
        }
        try {
            if (Integer.parseInt(year) > Calendar.getInstance().get(Calendar.YEAR)) {
                return "I libri che viaggiano nel tempo non ci piacciono";
            }
        } catch (NumberFormatException exception) {
            return "I libri che viaggiano nel tempo non ci piacciono";
        }
        return EMPTY;
    }
}

src/java/it/univr/booklovers/model/beans/UserBean.java
package it.univr.booklovers.model.beans;

import it.univr.booklovers.model.UserModel;
import java.io.Serializable;
import java.sql.SQLException;
import java.util.Objects;
import java.util.regex.Pattern;

/**
 *
 * @author blasco991
 *
 */
public class UserBean implements Serializable {

    private String coordinates;
    private String email;
    private boolean forEdit;
    private int id;
    private String image;
    private String name;
    private String password;
    private String postalCode;
    private String province;
    private String surname;
    private String username;
    private int views;
    private static final String EMPTY = "";
    private static final long serialVersionUID = 1L;

    /**
     *
     */
    public UserBean() {
        this.image = "img/profile-img.png";
    }

    /**
     *
     * @return
     */
    public String getCoordinates() {
        return coordinates;
    }

    /**
     *
     * @param coordinates
     */
    public void setCoordinates(String coordinates) {
        this.coordinates = coordinates;
    }

    /**
     *
     * @return
     */
    public String getEmail() {
        return email;
    }

    /**
     *
     * @param email
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     *
     * @return
     */
    public int getId() {
        return id;
    }

    /**
     *
     * @param id
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     *
     * @return
     */
    public String getImage() {
        return image;
    }

    /**
     *
     * @param image
     */
    public void setImage(String image) {
        this.image = image;
    }

    /**
     *
     * @return
     */
    public String getName() {
        return name;
    }

    /**
     *
     * @param name
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     *
     * @return
     */
    public String getPassword() {
        return password;
    }

    /**
     *
     * @param password
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     *
     * @return
     */
    public String getPostalCode() {
        return postalCode;
    }

    /**
     *
     * @param postalCode
     */
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    /**
     *
     * @return
     */
    public String getProvince() {
        return province;
    }

    /**
     *
     * @param province
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     *
     * @return
     */
    public String getSurname() {
        return surname;
    }

    /**
     *
     * @param surname
     */
    public void setSurname(String surname) {
        this.surname = surname;
    }

    /**
     *
     * @return
     */
    public String getUsername() {
        return username;
    }

    /**
     *
     * @param username
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     *
     * @return
     */
    public int getViews() {
        return views;
    }

    /**
     *
     * @param views
     */
    public void setViews(int views) {
        this.views = views;
    }

    /**
     *
     * @return
     */
    public boolean isLogged() {
        return this.id > 0;
    }

    /**
     *
     * @return
     */
    public boolean isNotLogged() {
        return !isLogged();
    }

    public String validateAction(String action) {
        this.forEdit = action.equals("edit");
        return EMPTY;
    }

    public String validateConfirmPassword(String confirmPassword) throws SQLException {
        if (!Objects.equals(password, confirmPassword)) {
            return "Le due password non coincidono";
        }
        return EMPTY;
    }

    public String validateCoordinates(String coordinates) throws SQLException {
        if (!coordinates.isEmpty()) {
            if (coordinates.length() < 3 || coordinates.length() > 64 || !(Pattern.compile("^(\\-?\\d+(\\.\\d+)?),\\s*(\\-?\\d+(\\.\\d+)?)$", Pattern.CASE_INSENSITIVE).matcher(coordinates).find())) {
                return "Coordinate non valide";
            }
        }
        return EMPTY;
    }

    public String validateEmail(String email) throws SQLException {
        if (email == null || !(Pattern.compile("^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$", Pattern.CASE_INSENSITIVE).matcher(email).find())) {
            return "L'email non è valida";
        } else if (email.length() > 256) {
            return "L'email è troppo lunga";
        } else if (!forEdit && UserModel.emailIsRegistered(email)) {
            return "L'email <" + email + "> è già registrata nel nostro sistema";
        }
        return EMPTY;
    }

    public String validatePassword(String password) throws SQLException {
        setPassword(password);
        if (forEdit) {
            if (!password.isEmpty() && (password.length() < 3 || password.length() > 256)) {
                return "La password deve essere compresa tra 3 e 256 caratteri";
            }
        } else if (password == null || password.length() < 3 || password.length() > 256) {
            return "La password deve essere compresa tra 3 e 256 caratteri";
        }
        return EMPTY;
    }

    public String validateUsername(String username) throws SQLException {
        if (username == null || (username.length() < 3 || username.length() > 64)) {
            return "L'username deve essere compreso tra 3 e 64 caratteri";
        } else if (!forEdit && UserModel.usernameIsRegistered(username)) {
            return "L'username <" + username + "> è già registrata nel nostro sistema";
        }
        return EMPTY;
    }

    public static String validateName(String name) {
        if (name == null || (name.length() < 3 || name.length() > 64)) {
            return "Il nome deve essere compreso tra 3 e 64 caratteri";
        }
        return EMPTY;
    }

    public static String validatePostalCode(String postalCode) {
        if (postalCode == null || !(postalCode.matches("[0-9]+")) || postalCode.length() != 5) {
            return "Il Cap non è valido";
        }
        return EMPTY;
    }

    public static String validateProvince(String province) throws SQLException {
        if (province == null || province.isEmpty()) {
            return "Seleziona la provincia";
        }
        return EMPTY;
    }

    public static String validateSurname(String surname) {
        if (surname == null || surname.length() < 3 || surname.length() > 64) {
            return "Il cognome deve essere compreso tra 3 e 64 caratteri";
        }
        return EMPTY;
    }
}

src/java/it/univr/booklovers/controller/frontend/BookServlet.java
package it.univr.booklovers.controller.frontend;

import it.univr.booklovers.controller.ServletModel;
import it.univr.booklovers.model.BookModel;
import it.univr.booklovers.model.UserModel;
import it.univr.booklovers.model.beans.BookBean;
import it.univr.booklovers.model.beans.CommentBean;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * Servlet implementation class ListaServlet
 */
@WebServlet(urlPatterns = {"/book"})
public class BookServlet extends ServletModel {

    private static final long serialVersionUID = 1L;

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response) {
        int id = 0;
        String book_id = request.getParameter("id");
        if (book_id != null && !book_id.isEmpty()) {
            try {
                id = Integer.parseInt(book_id);
            } catch (NumberFormatException ex) {
                exceptionHandler(ex, request, response);
            }
        }
        loadBook(request, response, id);
    }

    /**
     *
     * @param request
     * @param response
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response) {
        String action = request.getParameter("action");
        int book_id = 0;
        if (action.equals("comment")) {
            CommentBean commentBean = new CommentBean();
            try {
                book_id = Integer.parseInt(request.getParameter("book_id"));
                commentBean.setBook(BookModel.getBook(book_id));
                commentBean.setUser(UserModel.getUser(Integer.parseInt(request.getParameter("user_id"))));
                commentBean.setContent(request.getParameter("content"));
                DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
                Date date = new Date();
                commentBean.setDate_time(dateFormat.format(date));
                if (!commentBean.getContent().isEmpty()) {
                    BookModel.insertComment(commentBean);
                }
            } catch (SQLException ex) {
                exceptionHandler(ex, request, response);
            }
        }
        redirect("book?id=" + book_id, request, response);
    }

    private void loadBook(HttpServletRequest request, HttpServletResponse response, int book_id) {
        try {
            BookBean book = BookModel.getBook(book_id);
            if (book != null) {
                List<CommentBean> comments = BookModel.getComments(book_id);
                request.setAttribute("comments", comments);
                request.setAttribute("book", book);
                forward("frontend/book.jsp", request, response);
            } else {
                redirect("frontend/error_page.jsp", request, response);
            }
        } catch (NullPointerException | SQLException ex) {
            exceptionHandler(ex, request, response);
        }
    }

}

web/frontend/about.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>

<t:header>
    <jsp:attribute name="pageTitle">About</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="page-header">
            <h1>About us <small>Who we are</small></h1>
        </div>
        <div class="row text-center">
            <div class="col-sm-4">
                <img src="img/team/marian-solomon.jpg" class="img-circle" />
                <div class="caption">
                    <h3>Marian Solomon</h3>
                </div>
            </div>
            <div class="col-sm-4">
                <img src="img/team/luca-zidda.jpg" class="img-circle" />
                <div class="caption">
                    <h3>Luca Zidda</h3>
                </div> 
            </div>
            <div class="col-sm-4">
                <img src="img/team/cavazza-alvise.jpg" class="img-circle" />
                <div class="caption">
                    <h3>Cavazza Alvise</h3>
                </div>
            </div>
            <div class="row">
                <p class="lead">Kittenlovers è il nostro team di lavoro</p>
            </div>
            <div class="col-lg-6">
                        <img class="img-responsive img-thumbnail" src="img/love-books.jpg"/>
                    </div>
                    <div class="col-lg-6">
                        <img class="img-responsive footer-img center-block" src="img/booklovers_logo-200.png"/>
                        <p class="lead">
                            BookLovers è stato creato con le ultime tecnologie disponibili per risultare il più accessibile possibile.<br/>
                            Il layout del sito è completamente responsive e fruibile anche da dispositivi mobili come smartphone e tablet.<br/>
                            Enjoy yourself!
                        </p>
                        <a href="mailto:info@kittenlovers.com">info@kittenlovers.com</a>.
                    </div>    
        </div>
    </jsp:body>
</t:page_content>

<t:footer/>

web/frontend/book.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>
<%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>

<jsp:useBean id="user" class="it.univr.booklovers.model.beans.UserBean" scope="session"/>

<t:header>
    <jsp:attribute name="pageTitle">Book</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="row">
            <div class="page-header">
                <h1>${book.title}</h1>
            </div>
        </div>
        <div class="row page-header grid">
            <div class="col-lg-3 col-md-3 col-sm-4 col-xs-4 grid-item">
                <p class="lead">Scheda Tecnica</p>
                <div class="thumbnail">
                    <div class="caption">
                        <c:url value="search" var="url"><c:param name="author" value="${book.author}"/></c:url>
                        <p><label>Autore:</label> <a href="${url}">${book.author}</a></p>
                            <c:url value="search" var="url"><c:param name="genre" value="${book.genre}"/></c:url>
                        <p><label>Genere:</label> <a href="${url}">${book.genre}</a></p>
                        <p><label>Anno:</label> <a href="search?year=${book.year}">${book.year}</a></p>
                            <c:url value="search" var="url"><c:param name="publisher" value="${book.publisher}"/></c:url>
                        <p><label>Editore:</label> <a href="${url}">${book.publisher}</a></p>
                        <p><label>Lingua:</label> ${book.language} </p>
                        <p><label>Isbn:</label> ${book.isbn}</p>
                        <p>by <a href="profile?id=${book.owner.id}">${book.owner.username}</a></p>
                            <c:if test="${user.logged}">
                            <span class="btn btn-warning">
                                <a href="mailto:${book.owner.email}?subject=Richiesta Scambio libro da BookLoverS.com | Username: ${user.username}&body=Ciao ${book.owner.name}, sono interessato al tuo libro '${book.title}' dai uno sguardo al mio profilo per vedere cosa potrebbe interessarti. Attendo tuo riscontro."
                               target="_blank" class="lead text-white">Richiedi libro</a>
                            </span>
                        </c:if>
                    </div>
                </div>
            </div>
            <c:forEach var="image" items="${book.images}">
                <div class="col-lg-3 col-md-3 col-sm-4 col-xs-4 zoom-gallery grid-item margin-top-10">
                    <a href="${image}" data-source="${image}" title="${book.title}">
                        <img src="${image}" class="img-responsive"/>
                    </a>
                </div>
            </c:forEach>
            <c:if test="${empty book.images}"><div class="col-lg-3 col-md-3 col-sm-4 col-xs-4 zoom-gallery grid-item margin-top-10">
                    <a href="${image}" data-source="${image}" title="${book.title}">
                        <img src="${book.thumb}" class="img-responsive"/>
                    </a>
                </div>
            </c:if>
        </div>
        <div class="panel panel-default page-header">
            <div class="panel-heading">
                <h3 class="panel-title">Descrizione</h3>
            </div>
            <div class="panel-body">
                <p>${book.description}</p>
            </div>
        </div>
        <div class="row">
            <c:choose>
                <c:when test="${user.logged}">
                    <center>
                        <form action="book?action=comment" method="POST">
                            <label class="lead">Inserisci un commento</label><br/>
                            <textarea name="content" rows="3" cols="60"></textarea><br/>
                            <input type="hidden" name="book_id" value="${book.id}">
                            <input type="hidden" name="user_id" value="${user.id}">
                            <button type="submit" class="btn btn-primary">Commenta</button>
                        </form>
                    </center>
                </c:when>
            </c:choose>
            <br/>
            <c:if test="${empty comments}">
                <center class="lead">Non ci sono ancora commenti</center>
                </c:if>
                <c:forEach var="cm" items="${comments}">
                <div class="panel panel-info thumbnail">
                    <div class="panel-heading">
                        <h3 class="panel-title"><label>by</label> <a href="profile?id=${cm.user.id}">${cm.user.username}</a></h3>
                        <small>${cm.date_time}</small>
                    </div>
                    <div class="panel-body">
                        <p>${cm.content}</p>
                    </div>
                </div>
            </c:forEach>
        </div>
    </jsp:body>

</t:page_content>

<t:footer></t:footer>

web/frontend/error_page.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>

<t:header>
    <jsp:attribute name="pageTitle">Error</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="content">
            <div class="page-header">
                <h1>Errore di sistema</h1>
            </div>
            <div class="row">
                <div class="col-lg-4 jumbotron">
                    <p>
                        Ops, qualcosa non è andato a buon fine.
                        Ti preghiamo di riprovare ad aggiornare la pagine, 
                        se l'errore dovesse persistere provare a ricominciare 
                        la tua navigazione dalla <a href='homepage'>Homepage</a>
                        o contattare il nostro supporto tecnico 
                        <a href="mailto:info@kittenlovers.com">info@kittenlovers.com</a>.
                    </p>
                </div>
                <div class="col-lg-8">
                    <img class="img-responsive img-thumbnail" src="img/love-books.jpg"/>
                </div>
            </div>
        </div>
    </jsp:body>
</t:page_content>

<t:footer></t:footer>

web/frontend/homepage.jsp
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags" %>

<t:header>
    <jsp:attribute name="pageTitle">BookLovers.com</jsp:attribute>
</t:header>

<t:page_content>
    <jsp:body>
        <div class="page-header">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#myCarousel" data-slide-to="1"></li>
                    <li data-target="#myCarousel" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="img/slide/slide1.jpg" class="img-responsive" alt="Books">
                        <div class="carousel-caption backg-alpha">
                            <h2 class="text-warning backg-alpha-light">BookLovers.com</h2>
                            <p class="lead">Cerca i tuoi libri preferiti!</p>
                        </div>
                    </div>
                    <div class="item"><img src="img/slide/slide2.jpg" class="img-responsive" alt="Books">
                        <div class="carousel-caption backg-alpha">
                            <h2 class="text-danger backg-alpha-light">BookLovers.com</h2>
                            <p class="lead">Condividi il tuo patrimonio librario!</p>
                        </div>
                    </div>
                    <div class="item"><img src="img/slide/slide3.jpg" class="img-responsive" alt="Books">                        
                        <div class="carousel-caption backg-alpha">
                            <h2 class="text-success backg-alpha-light">BookLovers.com</h2>
                            <p class="lead">Incontra persone con i tuoi stessi interessi!</p>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                <div class="jumbotron text-center">
                    <h2 class="col-lg-7">L'ultima frontiera del booksharing!</h2> 
                    <img class="img-responsive" alt="bookLovers.com" src="img/booklovers_logo-200.png"/>
                    <p class="lead">Un progetto di kittenlovers, <a href="about">scopri chi siamo</a></p>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                <p class="lead">Ultimi libri inseriti</p>
                <ul class="media-list">
                    <c:forEach var="bk" items="${lastBooks}">
                        <li class="media">
                            <div class="media-left">
                                <a href="book?id=${bk.id}"><img class="media-object" src="${bk.thumb}" alt="Copertina"></a>
                            </div>
                            <div class="media-body media-middle">
                                <h4 class="media-heading"><a href="book?id=${bk.id}">${bk.title}</a></h4>
                            </div>
                        </li>
                    </c:forEach>
                </ul>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <h3 class="text-warning">Sharing</h3>
                <p>Su BookLovers.com hai la possibilita` di pubblicare il tuo patrimonio librario e di gestire una tua pagina personale</p>
            </div>
            <div class="col-sm-4">
                <h3 class="text-danger">Localizza</h3>
                <p>Su BookLovers.com puoi individuare utenti con i tuoi stessi interessi nelle tue vicinanze</p>
            </div>
            <div class="col-sm-4">
                <h3 class="text-success">Stalker</h3> 
                <p>Su BookLovers.com puoi fare dello stalking letterario!!</p>
            </div>
        </div>
    </jsp:body>

</t:page_content>

<t:footer/>